### ISSUE TITLE
Recipe: Uncaught Error: Invalid argument

### ISSUE THREAD

**Issue by Viseryn** [Viseryn/foodplanner#207]
`react-dom.development.js:12056  Uncaught Error: Invalid argument
    at fraction.js:381:1
    at ./node_modules/fraction.js/fraction.js (fraction.js:891:2)
    at __webpack_require__ (bootstrap:19:1)
    at ./assets/pages/ShoppingList/ShoppingList.tsx (ShoppingList.tsx:42:39)`

**Comment by Viseryn** [comment]
How to reproduce this error:

Create a recipe with ingredients. As last ingredient, just type "...". This will create an Ingredient object with "." as quantityValue.

Implement a validation for ingredients.
